# Generated by Django 4.1.5 on 2023-01-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('horario', models.TimeField()),
                ('local', models.CharField(max_length=50)),
                ('intensidade', models.CharField(max_length=20)),
                ('clas', models.CharField(max_length=13)),
            ],
        ),
    ]
